### ISSUE TITLE
Memory leak when using {{create-ref}}

### ISSUE THREAD

**Issue by tniezurawski** [lifeart/ember-ref-bucket#50]
Something is leaking when using `{{create-ref}}`. When running a memory snapshot after running tests I see an application hanging around. I was able to pinpoint it to this addon and `{{create-ref}}` usage.

![image](https://github.com/lifeart/ember-ref-bucket/assets/4335166/d66f52bf-4897-4a04-b84c-2d11add4ddb1)

The way I use it ([source](https://github.com/tniezurawski/ember-ref-bucket-memory-leak/blob/master/app/components/tomek-test.hbs)):

```hbs
<span {{create-ref "FavouriteNode"}}>Lorem ipsum</span>
```

## Steps to reproduce:
1. I created a minimal repo for reproduction. Please clone it -> https://github.com/tniezurawski/ember-ref-bucket-memory-leak

The repo is bare-bone. All I did was:
- creating a new Ember app
- adding `ember-ref-bucket`
- creating a test component (you can check there's no leak at this point)
- adding `{{create-ref}}` to that component

2. Run tests with this command: `ember test -s -f "Integration | Component | tomek-test"`. No more tests there but you'll be sure that you are running only the one.
3. Open Chrome devtools > Open Memory > click "Take snapshot"
4. Search for "Container" as this indicates an application instance hanging around
5. Select "Container" as on the screenshot and look at "Retainers". You'll find references to this addon

----

I didn't check yet why this is happening as I don't have knowledge about internals but I hope we can get it fixed together :)

**Comment by lifeart** [comment]
Hey @tniezurawski! Thank you for report! Likely it's related to global ref workaround https://github.com/lifeart/ember-ref-bucket/blob/master/addon/utils/ref.js#L17
there is no cleanup logic for it. We could try to register app destructor to null this ref

**Comment by lifeart** [comment]
@tniezurawski we have global ref for few cases:

1. If there is no context on template.
2. If we need to have access to DOM element from different parts of application.

Ideally, we need to set `globalRef` in application initializer (once), and create application level destructor to null it once application destroyed.

But, I don't remember why we don't have it in app instance initializer.. (maybe I'm lazy ass to write it initially).
That's why we set it in modifier, because once anybody use this addon, modifier will exist anyway.

Proposed fix looks good (binding cleanup to modifier cleanup, but may have side effects with multiple modifiers - first removed will `null` global ref and may cause runtime erros)

We could try do few things:

1. register destructor inside modifier, but binded to app instance (`getOwner(this)`).
2. implement app-initializer flow to register / remove globalRef
